### ISSUE TITLE
[NG-2021-16] Access Request

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#1073]
Lead developer: Jean-Come
The idea of this issue is to better manage the study data access and the user management, as new requirements and usage situations occured. These have been discussed during the consortium meeting 03.05.2022.

- **Most important**: we should go away from **account requests**, and move to **access requests**.
Users want to access to study data and an account is just a way to do this, but not the goal of the operation.
If an user is not at least member of minimum one study anymore, we should delete its account, as this user
can not get any data, but has access to the server, what is not ideal, but maybe even risky.
- The **study responsible** users are resposible for the members (study_user) in their studies. Any sysadmin can not judge, if an user X is allowed or not, each study responsible has to do that.
- Multiple solutions have been discussed:
1. **Expert request**: All, or specially flagged experts, could receive an access request from outside unknown people.
Users are created, but not yet active and only, when the access request is validated by the expert, the accounts are validated and activated. An existing user can using the home page ask again an expert with a free text field for more access.
2. **Study request**: Use the flag "visible by default" to show studies to the outside world, where acces can be asked from the home page or from outside unknown people (not yet users).

-- Initial issue, made by Elise
Hi, 
Following a discussion with Marion Richard (OxyTC study) we would like to suggest a functionality linking the Shanoir user administrator and the person responsible for the study. When accepting an account request to access a particularly study, the Shanoir user administrator needs to check (per email mostly) that the person responsible / principal investigator for the study agree with this request / that this user can access the study and with which role. Same thing happens with the extension request. Could we think of something there to avoid parallel emails and better track access granting ? 
Regards
Elise

**Comment by michaelkain** [comment]
An interesting idea, to simplify the code: https://github.com/fli-iam/shanoir-ng/issues/666

**Comment by michaelkain** [comment]
See my consortium presentation: Study Request or Expert Request

**Comment by ebannier** [comment]
+1

**Comment by jcomedouteau** [comment]
2 separates things:

Account request -> Account creation
Study access request -> Ask access to a study
Both will be independent (even if done at the same time).
There will be no more "administrator acceptation", only the studies managers will decide if a user can join or not the study.
I) New user
When creating a new request account the user will be able to create an access request on different studies.

Either from the list of 'public available' studies
Either from a text field the user needs to fill with a specific code associated to the study.
For every study, add a new column containing a code automatically generated.
The study administrator can give it to the new user so that he can request an access to the study.
When the study manager connects, he sees the study access demand and can accept/refuse it.

II) Existing user
When an existing user wants to join a study, he clicks on a button on the top of the study list to ask for an access. He has the same options as the new user:

Either from the list of 'public available' studies
Either from a text field the user needs to fill with a specific code.
StudyAccessDemand

Id
Date
Status
Motivation text
User ID
Study ID
Expiration date ?
The study administrator receives an email with the access request, and can choose to accept it or refuse it.
This response will be sent to the user in an email and will trigger the subscription (or not) of the user to the study.

Requirement: An user within no study should not be able to have access to anything in Shanoir
Solution 1: The account user is not activated (he can't connect) until accepted in a study -> This means an account demand must obligatorily contain an access demand.
If refused (no demands pending, no access to any study), the account will be deleted.

Solution 2: A (new) user linked to no study should be automatically redirected to the study access request page (and have access to nothing else).
For this, we create a keycloak key by user 'hasAccessToStudy' that will be updated if an user enters / leaves a study.
Then add an automatic "redirect" to this access page if the user has this key activated.
-> https://stackoverflow.com/questions/43487827/how-to-apply-canactivate-guard-on-all-the-routes (we redirect automatically to /accessRequest if no study)

TODO list:

Add visible by default on study (false by default) -> describe what is it for in front (XS)
Remove list of users for experts (cannot add an user to the study) -> Only for admins (XS)
Add study unique key system (generated once, the first time it is asked by the study manager) (XS)
Mix account request (challenge and not chalenge) and add access request to the page (M)
Add a page for access request (S)
Manage access request acception / refusal (+front) (M)
(1)
Add a "hasAccessToStudy" key on every keycloak user and manage it on user subscription/deletion from a study (M)
Redirect user with no study (S)
(2)
Activate an account only when the user is accepted in a study (XS)
Trigger account deletion when rejected / deleted from a study (and no other study / pending access demand) (XS)
What if a new user wants to create a new study ? Is it possible ? -> Not for the moment (newly created users will be 'users' until further news)

Other idea:
Add a notion of "Group of studies" that put multiples studies in a same logical entity.

An user can only see the users that are part of the realm/group
A newly subscribed user is part of all the studies of the realm/group
Split referential by group/realm (a center is modified only in its realm, referential is duplicated)
--> What about single study realms ? (Do they have to recreate all the referential ?)

**Comment by jcomedouteau** [comment]
New ideas discussed with MDojat:
- In shanoir login / homepage, display the list of "visible by default" studies and an associated short description of the study and its data.
- When doing an access request, the DUA should be presented first to the user, THEN the PI accepts the demand.
- Access to a study should have an expiration time
- Signed DUA should be stored somewhere even if the user account is disabled / deleted (for further juridical purpose eventually)

Access request and account request are no more linked
1) The user requests an access to shanoir
2) He does all the stuff needed to create its account
3) He connects -> He lands on the access request page by default
4) He makes an access request (+ DUA signing)
5) The PI receives an email, and accept the user FOR A GIVEN TIME
6) The user receives an email stating its acceptation
7) He can connect and see the study data.

**Comment by jcomedouteau** [comment]
(Ugly) pre-access of studies descriptions:
![image](https://user-images.githubusercontent.com/7604176/168839254-da0b4fc6-bbf5-4cb0-8230-37e3d5f367fb.png)

Access request page (add study description to it ?)
![image](https://user-images.githubusercontent.com/7604176/168841652-bb2b934c-1642-4772-a84d-608bda31396f.png)

**Comment by jcomedouteau** [comment]
**Principal objectives:**
- No more shanoir admin validation
- User is making access request for a study and the PI/study managers accepts/refuses the demand
- Some studies will be available / visible by default so that anyone can request access to it
- Study managers / PI cannot see all users anymore
- Study managers / PI can invite users to particpate to a study
- DUA are to be signed before the access request

_Different possible scenarios_

**Anonymous user**
- An anonymous user wants to join a public study, from the 'public catalog'
- He makes an access request to this study
- Along with it, he creates an account with all details -> The user is created in keycloak
- An email is sent to study administrators
- The study administrator connects and has a new notifications
- He opens the access request and accepts/deny it.
- He accepts -> The account is enabled, the user is added to the study -> An email is sent to the user
- He refuses -> The account request stays disabled -> An email is sent to the user

**Anonymous/disabled user with an invitation**
- A study manager / PI want to invite someone with no shanoir account to its study
- He fills a text field with the user's email adress
- If the user email exists, the user is directly added to the study (and enabled if prealably disabled) -> email sent to the user
- If the user email does not exists in shanoir, the user receives a mail with a direct link to create an account and join the study
- The user lands on the account request page and can create its account
- An email is sent to study administrators
- The study administrator connects and has a new notifications
- He opens the access request and accepts/deny it.
- He accepts -> The account is enabled, the user is added to the study -> An email is sent to the user
- He refuses -> The account request stays disabled -> An email is sent to the  user

**Existing enabled user wanting to join a study**
- An user with an account wants to join an existing study
- He goes on study list (or from home page) on the "access request" page
- He completes the access request
- An email is sent to study administrators
- The study administrator connects and has a new notifications
- He opens the access request and accepts/deny it.
- He accepts -> The account is enabled, the user is added to the study -> An email is sent to the user
- He refuses -> The account request stays disabled -> An email is sent to the  user

**Existing disabled user wanting to join a study**
- A study user with a disbled account wants to join a public study
- He goes from the catalog to make an access request
- He can choose to connect from here
- An email is sent to study administrators
- The study administrator connects and has a new notifications
- He opens the access request and accepts/deny it.
- He accepts -> The account is enabled, the user is added to the study -> An email is sent to the user
- He refuses -> The account request stays disabled -> An email is sent to the  user

**A user part of a study will expire soon**
- 2 weeks before the end of request access end, an email is sent to the study administrator
- An extension request is automatically created, the PI can accept it or refuse it
- He refuses: the user will be disabled (if only part of one study) and an email is sent
- He accepts: the user end date is extended -> email sent to the user


```
Access Request
- ID
- Creation_date
- Status (1=accepted 0=pending -1=refused)
- Motivation_text
- User_id
- Study_id
- Expiration date (set by the admin 1 year further of the creation date by default)
```

**Developments:**
- Add visible by default on study (false by default) -> describe what is it for in front (XS)
- Add a catalog of visible studies in the main page
- Mix account request (challenge and not challenge) and add access request int the login page (2 steps) (M)
- Add a page for access request detail + front notifications (S)
- Manage access request acception / refusal (+front) + emails (M)
- Activate an account only when the user is accepted in a study (XS)
- Trigger account disablement when deleted from a study (XS)
- Remove list of users for experts and add an invitation system that leads to access request page (or direct invite) (M)

**Further developments (not included)**
- The DUA is signed by the user during the access request (download / upload signed pdf verified by the PI)
- Groups of studies / realm that you can access all in one

**Comment by michaelkain** [comment]
I think we can close this issue, as implemented and now delivered. For all next version, we will create a new one.
