### ISSUE TITLE
Mass NIfTI conversion [NG-2023-02]

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1602]
- stop storing NIfTI files by default
- open for mass conversion of nifti files 
- e.g. used to harmonize big BIDS exports
- stop storing NIfTI files on the disk (storage size duplication), but propose the selection of
  a converter and download just-in-time converted NIfTI files, based on the DICOMs.
- Remove NIfTI converter from StudyCard and from all imports
- **Attention:** the constructed today available BIDS tree (symlinks to nifti files) will not exist anymore on the disk for download
- **Attention:** the conversion time can be long for a lot of datasets, so this will have to be managed
- **Attention:** we will need to manage, that NOT 10 users on the same study in parallel can run a full nifti conversion, what will be too much

**Comment by jcomedouteau** [comment]
The main idea of this feature is to convert the dicom files on the fly to get nifti files.
This will change the logic of following features:
- download nifti
- display preview in papaya
- BIDS export

For the moment we propose a single dataset nifti reconversion in DatasetApiController.
As nifti converters are stored in import microservices, the logic is:
1) Download dicom files from the dataset in a shared folder
2) Use rabbitMQ to communicate with import MS
3) In import MS, convert data using the selected converter and return the result folder
4) Get the result folder and send it back to download

This logic is correct for a single dataset, we may need to upgrade it for multiple datasets.

PART 1 Apply conversion logic for multiple datasets

Propose a new button to download in nifti with a specific converter
See the way it is done in single dataset download , when clicking on the button, the list of nifti converters is displayed.
Here we need to propose the "default" (the one in dataset_acquisition) converter (in green ?) and other converters.
In the back, convert the datasets either one by one, either all together (I don't know what's possible)
At the end of the process, delete the newly created niftis.

PART 2 Apply this conversion logic to download process and delete all existing nifti files on disk and associated dataset expressions
- Remove this new button, and apply the logic to all "download nifti" buttons.
- The error management should be bettered (to see what conversion failed)
- In papaya, load dicoms and not niftis
- Apply this logic when generating BIDS dataset -> When we generate it, we reconvert all datasets. Here we can imagine what we are going to generate the BIDS in the background, as, for some studies, the loading time will be very heavy.
- Add a warning about space usage when generating BIDS
- Propose a way to delete the BIDS structure (so that it does not take all space) -> also deleted when something is updated is the study.
- Remove all dataset expressions / files for niftis

**Comment by jcomedouteau** [comment]
Also we can put bruker2dicom in this microservice I guess.

**Comment by michaelkain** [comment]
Hi Jean-Come, thank you for your efforts. I agree principally to move NIfTI conversion to another microservice, fine, but above are quite a few points, we will have to exchange on. With kind regards, Michael

**Comment by jcomedouteau** [comment]
-> The admin can decide to make a full conversion + storage + tag in the study administration.
Camille: Can be a problem if we want to share the nifti files.
 -> The admin can decide to convert during import too (study parameter)

**Comment by michaelkain** [comment]
developed by Jean-Come
