### ISSUE TITLE
Optimize error management: front

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#2064]

**Comment by michaelkain** [comment]
1. Analyze today's error management, e.g. in my Firefox I can not open and see correctly all errors. How to fix this?

**Comment by michaelkain** [comment]
![Screenshot from 2024-02-07 15-48-30](https://github.com/fli-iam/shanoir-ng/assets/4560288/08d87fcb-e6c9-4339-af55-28448bc4546b)

**Comment by pierrehenri-dauvergne** [comment]
This is what I have on windows + firefox:
![image](https://github.com/fli-iam/shanoir-ng/assets/117283961/bb4e41f9-1f9a-4473-b638-7cb64683ab4e)

I can click the arrow, so that the console take the whole width of the page and I can scroll in the console as I want to.
The issue is that you do not have the " > " arrow ?
