### ISSUE TITLE
WebGUI: manage subjects: error: loads study list

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#2074]
Hi Pierre-Henri, I hope you are doing fine.
On the subjects page, where we list all subjects in the web GUI, a get-request is sent to get all studies.
Nothing at all on studies is displayed on the page. I think this is an error. Please see my screenshot.
Thank you and with kind regards, Michael
![Screenshot from 2024-02-08 08-44-22](https://github.com/fli-iam/shanoir-ng/assets/4560288/01c254f5-a433-44e2-99c4-9cc1c51ea036)
PS: ignore the empty subjects list in the screenshot, related to my local dev. The behaviour is the same on qualif and prod, where the subject list works.

**Comment by michaelkain** [comment]
same here: why do we call the coils list, if never displayed and used, when I open the tree, all is search again
![Screenshot from 2024-02-08 10-14-13](https://github.com/fli-iam/shanoir-ng/assets/4560288/3378099d-2b7e-4995-9317-5abf8c438793)

**Comment by michaelkain** [comment]
again, ignore the error: the problem is, why do we call /coils? the error comes from my local dev

**Comment by pierrehenri-dauvergne** [comment]
/studies is called because if you want to delete a subject, you can either be shanoir admin or have admin rights on the study in which the subject is

/coils is called because in the Tree tab, you can see equipment for each centers of the study. This is data that is not brought back from the study details
