### ISSUE TITLE
Add a job for long tasks

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#2188]
Tasks the can last a long time should have a Job to show the user that it still going on. The gear icon on the top right corner is not visible enough

Long tasks I'm thinking of (they are probably other) are:
- Deletion of examination
- ~~Statistics export~~
- ~~Index of solr~~

**Comment by youennmerel** [comment]
+ statistic export
Index to Solr => Done in https://github.com/fli-iam/shanoir-ng/pull/2206

**Comment by michaelkain** [comment]
Hi @pierrehenri-dauvergne, I hope you are doing fine.
In case during my absence, there might be some time left, it would be great to work on these.
Especially the stats export might be a good point as we have a data manager, that can not download
the stats because of the hospital network (5 min proxy timeout on requests), and propose him the stats
once the job is finished. With kind regards, Michael

**Comment by pierrehenri-dauvergne** [comment]
Stats export => [#24](https://github.com/fli-iam/shanoir-ng/pull/2416)

**Comment by pierrehenri-dauvergne** [comment]
Delete of examination => https://github.com/fli-iam/shanoir-ng/pull/2442
