### ISSUE TITLE
Challenges: migrate PET (TEP) import from challenges branch into sh-ng

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#252]
For the PET (TEP) challenge MICCAI 2016 we integrated a TEP data import into sh-ng.
As we do not want to lose this modality in sh-ng, the code should be migrated to sh-ng.
This applies to the import code and to the data model extension.
So after that sh-ng will support MR, EEG, Bruker, Spectroscopy and TEP modalities.

**Comment by michaelkain** [comment]
Hi Yao, I assigned you the issue as you have been developing the feature originally. We will see when we work on it.

**Comment by michaelkain** [comment]
discussed with Irène

**Comment by michaelkain** [comment]
Hi Yao, could you please search your old code in shanoir-challenges branch PETDataset, with its attributes defined together with Mathieu Hatt and migrate it to sh-ng? Could you please propose me at first a task list and a specification on the Wiki how you consider working on this, and your estimation of time please? Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
Julien has recently done exactly the same thing for CTDatasets, so please follow his example. Thank you, Michael

**Comment by yyao1231** [comment]
Hi @michaelkain the specification could be found on the wiki: https://github.com/fli-iam/shanoir-ng/wiki/PET
Feel free to share it with interested people and to discuss.

**Comment by michaelkain** [comment]
Hi Yao, have you analysed if your 6 fields mandatory are mandatory in the dicom files? For PET imaging concerning the dicom standard what "type" do they have? Are some of them mandatory already in dicom? To progress with the development, I propose to implement the import of the PET images in the assumption that all 6 fields will be present. We will have to do this work anyway. When this works and your PR is there, we can extend it if necessary for the edition of the 6 fields as all the code of your first PR will be usable.

**Comment by michaelkain** [comment]
e.g. 

Tag | (0028,0010)
-- | --
Required (1)

is mandatory in the dicom, why should it be missing?

**Comment by yyao1231** [comment]
Thanks for you comment Michi. It is interesting. Not all of the 6 fields are required by Dicom standard. Actually, we asked Mathieu Hatt the same question years ago and here is his response: "all of this is somewhat non standard meaning that DICOM fields may be different from one system to another, or from a vendor to another
so it is difficult to specify which DICOM tags is supposed to be found, as it depends on the actual system/vendor configuration". So that's why in the spec of 2015, we made difference between "mandatory for challenge" and "would be good for future PET data in shanoir" for the dicom tags.

**Comment by yyao1231** [comment]
I agree with you that to progress on dev, I'll consider the 6 fields all present for the moment. 
So for the dev, I will only display these fields for the moment, and the edition will come later if not all of them are present.
