### ISSUE TITLE
Challenges: migrate static data export: Shanoir-NG -> VIP

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#254]
This static export has already been developed and should be migrated into sh-ng. The idea is for the challenges, that we transfer once the images for processing to VIP containing back-references in .json format (to know where to put the processed datasets) back into sh-ng. This avoids transferring big amounts of data for each execution to VIP, what means the original images for processing a copied and duplicated in VIP only one time and can there be used multiple times.

**Comment by michaelkain** [comment]
maybe we could use BIDS export to optimize this and avoiding double development

**Comment by michaelkain** [comment]
Hi J-C, I have assigned you not for development, but for answering a question. Is there a way to know in the BIDS export, where in sh-ng the data came from -> datasetId? I am asking this as for the challenges, when we once transfer the data to VIP for re-importing the results, processed data we will have to know the origin dataset ids to attach them.

**Comment by jcomedouteau** [comment]
Michael,
I don't think we currently use the dataset ID anywhere in the BIDS export, but we can imagine using it in a metadata field.
If you look at 
[https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#dataset_descriptionjson](https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#dataset_descriptionjson)
in dataset_description.json, there is a field 
> DatasetDOI: The Document Object Identifier of the dataset (not the corresponding paper).

If I understood well what we want, we could easily use it. Otherwise let's discuss this during the daily!
