### ISSUE TITLE
[MS Datasets] Zip file name when downloading dcm or nii files

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#272]
Today sh-ng generates a random number as zip file name for dcm/nii files download. 
In sh-old, the zip file name seams as subjectName_datasetComment_xxxx. 
Do we need to define some file naming "protocol", maybe inspired from sh-old or BIDS?

**Comment by jcomedouteau** [comment]
If we export a single dataset, there is no specific rule with BIDS.
It could be interesting to have an identifier on shanoir entities, that are unique and understandable for a user and/or modifiable by the user. (and initially computed in the code)

**Comment by ebannier** [comment]
If I may comment there, in the minutes of our last meeting (March 20th 2020), I described the different ways the nifti files are named, when accessed with 3 different ways : 

manage my research studies : NomSujet_SeriesDescription_SeriesNumberInProtocol_SeriesNumberInSequence.nii : 1RO100 ND 183_T2FLAIRAXIALs006a001.nii
Dataset : 
Single file : just like via manage my research studies eg : 1RO100 ND 183_T2FLAIRAXIALs006a001.nii
Several files : Selection.tar selection2937655924978595908.tar containing .zip files named Nifti-single-file.1RO100_ND_183.T2_FLAIR_AXIAL.id121826.dcm2nii_2008-03-31.zip containing 1RO100 ND 183_T2FLAIRAXIALs006a001.nii 
In the last case it would be better to have a tar of nii.gz rather than zip which contains nii and are named differently. 

Besides, nifti file name should contain subject name in the study (common name), series number (allows to identify acquisition order and repeated sequences), and visit number if any (M0, M6) to allow massive download. 

Can you confirm this is ok for you?

**Comment by michaelkain** [comment]
Hi Jean-Come, could you work on this naming scheme next week, asked by Elise? Thank you, Michael
