### ISSUE TITLE
Config of nginx: protect access to Solr admin GUI, PACS GUI, RabbitMQ GUI

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#445]

**Comment by jcomedouteau** [comment]
Do I limit the access only from localhost (which is the case for rabbitMQ GUI at least) that allows us to tunnel and connect, or do I restrict everything ?

**Comment by michaelkain** [comment]
from my point of view everything can be accessible using localhost, the point is to protect outside access via nginx;
that docker-compose exposes locally on using localhost is not a problem
so calling localhost:xxxx (not nginx, only on 443, as direct access) is not a problem
using https://shanoir-ng-nginx/shanoir-ng/solr/---admin-gui-url or similar should be protected and not possible

**Comment by jcomedouteau** [comment]
I've been trying to access to these on the qualif but I could not
=> Keycloak is protected (see nginx configuration) not to accept /auth/admin/ requests (so you cannot access to admin interface)

> #
> # Keycloak
> #
> # forward (reverse-proxy) all requests for /auth/* to the Keycloak server
> location /auth/ {
> 	proxy_pass	http://SHANOIR_PREFIXkeycloak:8080/auth/;
> 	# protect admin web interface from outside access
> 	location = /auth/admin/ {
> 		return 404;
> 	}
> }

I don't have access to rabbitMQ, solr and PACS GUI on the qualif server => They are using another port (8983 for solr, 15672 for rabbitMQ, 8081 for PACS).
I don't really know if this is linked to nginx only listening to port 80 or to the fact that all these are using http and not https.

When using shanoir-ng-nginx, we have access to them because we have a DNS resolution in 'hosts' from shanoir-ng-nginx to localhost, but this should not work on the qualif/prod.

So we can:
- Keep it like this
- Use a firewall (iptables) to block totally access to ports => Nginx does not seems to be the best tool to limit access to a port
- Another idea ?

What do you think of it ?
Thanks

**Comment by jcomedouteau** [comment]
All access to rabbitMQ, PACS, solr and keycloak are disabled. I'm closing this issue.
