### ISSUE TITLE
OFSEP: monthly reporting

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#495]
The idea is to "migrate" the monthly report for Ofsep to Shanoir-NG. Today the report is constructed using a SQL script on the database, that joins the following tables, and streams the result into a TXT file:

from SUBJECT as sb
inner join REF_SEX as sex
inner join PSEUDONYMUS_HASH_VALUES as pseud
inner join STUDY as st
inner join CENTER as cnt
inner join MANUFACTURER as man
inner join MANUFACTURER_MODEL as man_mod
inner join MANUFACTURER_MR_MODEL as man_mr
inner join ACQUISITION_EQUIPMENT as ac_eq
inner join MR_PROTOCOL as pr
inner join EXAMINATION as ex
inner join DATASET as dt
inner join REL_SUBJECT_STUDY as rel_sb_st
inner join DATASET_ACQUISITION as dt_acq
inner join MR_DATASET_ACQUISITION as mr_acq

As within Shanoir-NG these tables are split between two database schemas: MS STUDIES + MS DATASETS, we need to find a solution for this. The idea of this issue is:

- Write a specification within the GitHub wiki, that drives the implementation 
- Collect the possible implementation solutions to provide the same result as today with Shanoir-NG, and estimate their time
- Specify and discuss a potential solution using the GUI web of Shanoir-NG to allow "admin" user types to directly download this report or even have a display of these numbers
- Think of a potential usability of this report for other users too, e.g. Neurinfo

**Comment by michaelkain** [comment]
not to forget the encryption PGP

**Comment by arthursw** [comment]
For the spec: is it possible to have a SQL script, that works on two database schemas? 

From this answer on stackoverflow it seems quite simple:

    SQL Server allows you to join tables from different databases as long as those databases are on the same server. The join syntax is the same; the only difference is that you must fully specify table names.

    what columns have been changed? do not exist maybe?


    will it be better to code the query into Java JPA using native query? Spring Batch? stored procedure on the MySQL db? will we need views to optimise
    performance maybe? If in Java code: how do we manage, that we have two micro services and two data models? will we have to use RabbitMQ to synchronise between MS?
    will it be possible, that MS Studies prepares data, e.g. on the disk or in a RabbitMQ message, and that MS Datasets completes the data to produce the „CSV“ file?

Since it seems quite simple to use SQL, I suppose we can forget the java solution? Anyway it should be possible to execute the same SQL queries from java (so query on 2 different databases from the same micro service)?

    How big in lines is the export today already, how long does it require to run on the db?

The last export has 138 302 lines, and a size of 119M. It takes a bit less than 15 seconds to execute.

    How long will the merging need of develop branch into boutiques branch?

It shouldn't bee too long to compile, the long part will be the testing.


    To test the reporting, it should be fine with one import on one study, at first, to see if the code works functionally. When the migration scripts have been
    finished from my side, we can use shanoir-ofsep-qualif to test with real data.

**Comment by michaelkain** [comment]
Your stack overflow post is talking about SQL Server product from Microsoft, what is not
the MySQL we are using, but I verified on another site, that using the schema name within
the sql query could be a solution for us with MySQL. So, it looks, that just adapting the query
could be quite fast to realise (1-2 days).

**Comment by michaelkain** [comment]
https://www.unityjdbc.com/doc/multiple/multiplequery.php

**Comment by arthursw** [comment]
Woups, sorry about the wrong stackoverflow answer :/

**Comment by arthursw** [comment]
We decided to create a button in the front (only visible by admins) which calls an API endpoint in Datasets which executes the MySQL script, and returns the resulting file to the client (to download the ~130Mb file).

**Comment by arthursw** [comment]
In shanoir-ng it seems there are two columns to match a dataset with its metadata: `updated_metadata_id` and `origin_metadata_id` (to get the name and the comment of the dataset). Which one should I use?

**Comment by arthursw** [comment]
I see that the Dataset controller of the datasets service returns the updatedMetadata name if it exists (and is not empty) otherwise the originMetadata name if it exists and is not empty, otherwise creates a name of format `[id] [creation date] [type]`. 

What should I return in the script ? 

I'll just use the updatedMetadata name for now. I could also return both (thus creating another column, meaning OFSEP would probably have to update their script).

**Comment by michaelkain** [comment]
Hi Arthur, please use updatedMetadata, as these are the result of the StudyCard application and should therefore be more correct/harmonised than the originMetadata.

**Comment by arthursw** [comment]
All right!
So I created a script which runs without error. Yet I cannot test it completely without real data: the default test data has all `updated_metadata_id` set to NULL. Do you need some help for the migration scripts?

**Comment by arthursw** [comment]
How should I name the API endpoint? `downloadStatistics`? `downloadDatabaseDump`? 

I am currently adding the endpoint in the `datasets` API, but I could also use `studies`, what do you think?

**Comment by michaelkain** [comment]
Hi Arthur, downloadStatistics sounds good for me. And I would prefer datasets API too. Please add a mechanism to the web GUI, that users can not send multiple requests, when waiting for the result, because this could easily slow down the entire system, and display some work in progress. Jean-Come had the case with Grenoble testers, that clicked multiple times for data download...

**Comment by arthursw** [comment]
All right, I'll do that!

**Comment by michaelkain** [comment]
This one could be interesting: https://stackoverflow.com/questions/46510635/export-solr-data-to-csv-or-excel
Maybe it would be not so difficult to use RabbitMQ to complete the infos as pseudo, center, etc. and to feed all
infos into Solr index, and to export that to CSV... please continue with the stored procedure, we will see how fast
it goes and discuss together.

**Comment by michaelkain** [comment]
https://stackoverflow.com/questions/3591258/how-to-dump-backup-a-solr-index-to-a-file

**Comment by arthursw** [comment]
I thought about a simple way to select which studies to consider in the export. Here is what I came up with:

I will do a dialog box in the front which will ask for a string to filter out the studies by name with a regex.

So the OFSEP will have to enter the string "Cohorte Principale*|CISCO_Nimes" to get their current export.
And any user can change this string to fit their need.

Subjects 'TestDummyRun*' and 'test*' will always be excluded from the export.

What do you think?

**Comment by michaelkain** [comment]
Sounds good to me. Could you make the exclusion list variable+editable too? so with Neurinfo or other studies people could exclude what they want; as I am not sure that the exclusion from Ofsep applies to all studies.

**Comment by arthursw** [comment]
Well, for now the exclusion is on *subject names*, whereas the regex filter is on the *study names*. 

But I could add a study name exclusion field if that's what you mean 👍 

Yet, I must check that this regex parameter is secure and protected against code injection hacks. 

Since the regexp can contain exotic characters, the api endpoint parameters must either be in the body of the request (the client sends a json) or maybe in the URL (as query params for example) but I would need a way to handle weird chars in the URL.

**Comment by arthursw** [comment]
Thinking about it, it does make much sense to add a filter out regex for study names...

**Comment by michaelkain** [comment]
Sorry, I was not clear. What I meant:
- study names field, with regexp: [Cohorte Principale*|CISCO_Nimes] (what studies to include)
- subject names field, with regexp: [TestDummyRun*|test*] (what subjects to exclude)

**Comment by michaelkain** [comment]
so if somebody wants to have stats only for one study, he enters "mystudy" and nothing into subject names field,
if he wants to exclude a subject, he can, or more

**Comment by michaelkain** [comment]
BUT, if too complicated, just the script as it is today

**Comment by arthursw** [comment]
I assumed it was not clean to show that there is test data to everybody, that's why I didn't give the possibility to filter subjects...

I feel it would be cleaner to have both regex filter working the same way, (both "inclusive") but MYSQL does not support the `(?!)` operator in regexp ; meaning it is not simple.

So one way would be to have 4 fields: 
```
where subject.name rlike subjectNameInFilter
    and subject.name not rlike subjectNameOutFilter
    and study.name rlike subjectNameInFilter
    and study.name not rlike studyNameOutFilter;
```

it's a bit complicated but is quite flexible.

**Comment by michaelkain** [comment]
Hi Arthur, the above is fine for me. Stéphanie confirmed me their interest in a download button within sh-ng, to access to the report directly. She is asking if there would be a possibility to extend the report with slice thickness and acquisition matrix infos (to discuss impact between us)?

**Comment by arthursw** [comment]
All right!
It's possible to add more filters, it will just take some time to implement.

**Comment by jcomedouteau** [comment]
Solved by @arthursw  !
