### ISSUE TITLE
All datasets api

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#548]
@albangaignard needs an api to get every dataset he has access to without paging. For now there is a paging cap at 2000 elements.

* We should develop a new api.
* Should we raise the cap to, let's says 1 000 000 as a quickfix so it would be possible to tech a giant page with every dataset in it?
* Alban, were you happy with the former data structure? Was there useless data or missing ones that you would like to get from that request ?

**Comment by albangaignard** [comment]
Thanks for reporting this issue. 

I don't thnk a new API is needed. Keeping pagination is a good idea, that would be nice to describe in the doc how to access next pages. For now I can only access page 1. 

I was happy with the last data structure. I'm just missing DICOM metadata informing on the content. I'm trying to filter only 3D TOF images, with reasonable number of slices. In the ICAN study, a lot of images are not TOF modality nor 3D volumes. 

That's quite urgent since if not avaliable, I need to transfer images and parse DICOM metadata. This can be quite overwhelming both for the Shanoir server, and for our local computing infra.

**Comment by Nunien** [comment]
To access the next pages you just have to increment "page" (that's the number of the page)

https://shanoir-ng-nginx/shanoir-ng/datasets/datasets?**page=0**&size=20&sort=id,DESC
https://shanoir-ng-nginx/shanoir-ng/datasets/datasets?**page=1**&size=20&sort=id,DESC
https://shanoir-ng-nginx/shanoir-ng/datasets/datasets?**page=2**&size=20&sort=id,DESC

You can also increase "size" to have larger pages.

**Comment by albangaignard** [comment]
Ok, perfect, so that's easy to crawl. Thanks !

**Comment by Nunien** [comment]
TODO (for me) : write doc about that in the wiki

**Comment by Nunien** [comment]
Done : 
https://github.com/fli-iam/shanoir-ng/wiki/Dataset-Rest-API
