### ISSUE TITLE
nii or nii.gz ? 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#556]
This is more a question than an issue : nifti download yields nii files and not nii.gz. Have you thought of yielding nii.gz to save space?

**Comment by michaelkain** [comment]
to discuss, I am not sure if double compression helps us gain any space, maybe I am wrong

**Comment by jcomedouteau** [comment]
I'm on it to check
- If we gain space
- if it changes a lot in the code
- If we can use it for all converters

**Comment by jcomedouteau** [comment]
With dcm2niix:
For small images, we gain ~20% of space (34M => 26M)
For "big" images, we can gain up to 70% of space (226M => 69M)

For dicomfier => up to 50%

There is a real gain of space.

mcverter => Not possible to go to create .gz

Concerning the code:
-> Papaya.js accepts both nii & nii.gz
-> Bids accepts both nii and nii.gz

Changes:
ShanoirExec (to configure converters)

Otherwise the code seems quite resilient about it.
=> I'll have to change my PR to import from nifti too (to accept .nii.gz file)

**Comment by Nunien** [comment]
@jcomedouteau So the test is : 
* dl nifti before this pr : nifti files
* dl nifti after this pr : nifti.gz files, the size is lighter + check papaya
?

**Comment by jcomedouteau** [comment]
@Nunien Not exactly.
Before this PR
- Upload some data with dicomifier or dcm2niix
- Download them and check papaya -> it's .nii

After this PR
- Upload some data with dicomifier or dcm2niix
- Download them and check papaya -> it's .nii.gz

**Comment by Nunien** [comment]
@jcomedouteau thanks !
