### ISSUE TITLE
Import warning 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#621]
Hi, 

Could you tell me if the warnings in the screenshot attached appear systematically or only if there is a mismatch? 
![Warnings_ShanoirNG](https://user-images.githubusercontent.com/36895591/97155049-0b1d1580-1775-11eb-8f03-4803590729fe.png)
To me it should only appear when there is a mismatch and in the import I was doing the device selected was correct so I do not expect a mismatch. This is misleading, especially for new users, 

Thanks in advance for clarifying,
Elise

**Comment by michaelkain** [comment]
Hi, the warning is only displayed if there is a mismatch. Your archive does not contain any center information in the dicoms, probably anonymised before, nor does it contain a device serial number in the dicoms, what leas to the second warning. With kind regards, Michael

**Comment by ebannier2018** [comment]
Hi, 
The data is not anonymized before, the device serial number is correct, maybe the name of the vendor is slightly different (Siemens XXYY or Siemens) but this should not give a warning. We already discussed this a few months back. Serial Number should be sufficient to check for MRI, but other fields had been added because some CT acquisition equipments were created in Shanoir without a serial number / dit not have one 
Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by michaelkain** [comment]
Hi Elise, could you precise, if the above issue appears with a zip dicom import or using the Neurinfo PACS with query/retrieve? As I wrote above, the issue is, that in the dicoms does not seem to be the serial number, see the line
"Your archive contains this data: vendor - machine - serial number", **as serial number is empty** the warning is displayed. We will have to clarify with an example, please share it with us, if for a not very probable reason, Shanoir does badly manage the serial number (normally I saw it already working), or if for whatever reason your data do just not contain a serial number. Thank you and with kind regards, Michael

**Comment by jcomedouteau** [comment]
This was corrected as possible -> We tried to match the serial number, then the center/machine name if existing.
Otherwise, the warning will appear.
