### ISSUE TITLE
Prod: dicom import: error: phantom: use exam date instead of birth date for subject creation

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#630]
Something weird happening with the Birth Date, also if we select Phantom instead : 01012020, while we expect the acquisition date, does this explain the error, with the import (see the mail from EB)

**Comment by ebannier2018** [comment]
I was in a rush when I sent you the email. We usually set the phantom to 30 years old and birth date is entered accordingly but this is not the issue. Somehow we could not perform the import for this dataset and we do not know why.

**Comment by michaelkain** [comment]
Hi Julien, could you please start to work on that? Please check in the logs, where the problem comes from, I guess there are some dicom data missing/formatted differently?

**Comment by Nunien** [comment]
Ok but I want to discuss it at the dsu as the problem is not clear to me for the moment

**Comment by Nunien** [comment]
Ok so if I understand, a phantom bithdate should be the acquisition date.

**Comment by ebannier2018** [comment]
No, that is not the problem. 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by ebannier2018** [comment]
And I do not know where the problem comes from either...do the logs give some kind of info? 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by Nunien** [comment]
@ebannier2018 Can you tell me the date + aproximate hour of that failed import ? Also, if you can try the import yourself and if you have a moment, it will be great to have a call so you can show me the bug.

**Comment by ebannier2018** [comment]
We can have a call now ? On discord? 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by Nunien** [comment]
After a call with @ebannier2018 , it appears that there is a 500 error from the sibject save api due to the absence of sex for a already anonymized subject : 

```
{"code":500,"message":"Could not read document: Can not deserialize value of type org.shanoir.ng.subject.model.Sex from String \"O\": value not one of declared Enum instance names: [M, F]\n at [Source: java.io.PushbackInputStream@1d5131d; line: 1, column: 251] (through reference chain: org.shanoir.ng.subject.model.Subject[\"sex\"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type org.shanoir.ng.subject.model.Sex from String \"O\": value not one of declared Enum instance names: [M, F]\n at [Source: java.io.PushbackInputStream@1d5131d; line: 1, column: 251] (through reference chain: org.shanoir.ng.subject.model.Subject[\"sex\"])","details":null}
```

Here is a workaround though : just select a sex before switching to "already anonymized" (which hides the sex field).
Then one can remove the sex by editing the subject.
