### ISSUE TITLE
[Study-tree review] new issues

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#646]
> Download buttons should only appears when viewing study

It's OK I corrected this in my pull request

**Comment by michaelkain** [comment]
**/ false** behind each dataset (serie dicom), e.g.  **3dTof 1 / false**

**Comment by jcomedouteau** [comment]
View studycard detail from study tree => error

Because of route study-cards instead of study-card

**Comment by michaelkain** [comment]
3D T2 FS **()** behind each exam

**Comment by jcomedouteau** [comment]
As expert, from examination no access to dataset list in tree

message: "Failed to evaluate expression 'hasRole('ADMIN') or @datasetSecurityService.filterDatasetAcquisitionList(returnObject.getBody(), 'CAN_SEE_ALL')'"

**Comment by michaelkain** [comment]
study details (studyId 178) - click on 001 patient and try to download dicom of first dataset -> error

**Comment by michaelkain** [comment]
user type User, all rights in study, study details (studyId 178) - selected 3 datasets of patient 001, click on selected datasets -> error to choose dataset type (see my 2nd mail)

**Comment by michaelkain** [comment]
issue: icon in menu for examination is not the same as in tree

**Comment by jcomedouteau** [comment]
When downloading from dataset detail in study-tree => download launched twice. Due to element cliocked in <span> ?

**Comment by michaelkain** [comment]
@Nunien Hi, when could we fix a next test session for these corrections? With kind regards, Michael

**Comment by Nunien** [comment]
* / false behind each dataset (serie dicom), e.g. 3dTof 1 / false ... :ok: 
* View studycard detail from study tree => error ... :ok:  
* 3D T2 FS () behind each exam (actually behind dataset acquisitions) ... :ok:
* As expert, from examination no access to dataset list in tree ... :ok: 
*  issue: icon in menu for examination is not the same as in tree ... :ok: 
* When downloading from dataset detail in study-tree => download launched twice. Due to element cliocked in ? ... :ok: 
* user type User, all rights in study, study details (studyId 178) - selected 3 datasets of patient 001, click on selected datasets -> error to choose dataset type (see my 2nd mail) ... :-1:  could not reproduce
