### ISSUE TITLE
An unexpected error occured

### ISSUE THREAD

**Issue by rhedouin** [fli-iam/shanoir-ng#669]
Hi, 

I'm trying to import data from Amynet, it worked when I downloaded the Bids. Yet, I'm not able to import the Dicom, I tried multiple times with different images and subjects, and I always have the following error.
An unexpected error occurred

Thanks for your help, 
Renaud

**Comment by jcomedouteau** [comment]
Mr Hedouin,

Could you please describe us the precise steps to reproduce the problem ?
=> What kind of import do you use ? Bids or Dicom ?
=> At which step does the import fails ?

And could you eventually send a sample of the images failing directly to Michael Kain (michael.kain@inria.fr => do not publish it here directly as it is a public repository) so that we can reproduce the problem and investigate it ?

Thanks a lot and have a nice day,

Jean-Côme Douteau for the Shanoir development team.

**Comment by rhedouin** [comment]
Hi,

Thanks for this fast response. Here a screenshot of what occurred (it
should summarize the problem more efficiently than I would explain it).

Best regards,
Renaud

Le mar. 24 nov. 2020 à 12:08, jcomedouteau <notifications@github.com> a
écrit :

**Comment by jcomedouteau** [comment]
Me Hedouin,r
I can't see the screenshot, did you send it to Michael Kain directly ?
Thanks!

Jean-Côme
