### ISSUE TITLE
remove examinations 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#671]
je dois supprimer des examens dans l'étude NEUROFB_AVC car il y a eu une erreur de nommage (les sujets passent plusieurs fois et ont été importés séparément au lieu d'être groupés sur un seul sujet, et le sujet renommé par erreur dans Shanoir en S2 pour l'un des deux --> l'import a été refait correctement pour ce sujet et je dois supprimer les examens du sujet qui apparait comme S2 dans le détails des examens via Studies, mais il n'apparait pas via Sujet. Avant je passais par le menu Examinations pour supprimer les ids en question mais quand je clique sur la corbeille j'ai un message d'erreur. 
Il s'agit des ids : 13190; 13191, 13251, 13270, 13375. Pouvez vous regarder ce qui cloche là aussi ?

**Comment by jcomedouteau** [comment]
@ebannier2018 Pourrais tu m'ajouter sur l'étude concernée que je regarde? Merci !
Jean-Côme

**Comment by jcomedouteau** [comment]
Ok I found the problem, thanks Elise.

When deleting an exam in ExaminationApiController we try to get access to data path:
    String dataPath = examinationService.getExtraDataFilePath(examinationId, "");
Which leads to:

Failed to evaluate expression 'hasRole('ADMIN') or (hasAnyRole('EXPERT', 'USER') and @datasetSecurityService.hasRightOnExamination(#examinationId, 'CAN_DOWNLOAD'))'

Because the examination is deleted before.

So first delete the extra data files then delete the exam..
