### ISSUE TITLE
[NG-2021-3] Study Configuration (technical)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#703]
Hi,
we could add a new tab into view/edit study to configure each study:
I think in the future in any case, technical administrators will configure study specific technical configurations, like
- which anonymization profile is used for the imports per study
- configure if during the import a patient with an existing identifier (is preselected per default and can be changed or not)
- configure what subject_identifier hash algorithm should be used (OFSEP: pseudonymus, Neurinfo: basic hash)
- maybe what is the default nifti_converter per study
- maybe a user agreement form to sign before access to the data

**Comment by jcomedouteau** [comment]
2 separates things:
- Account request 		-> Account creation
- Study access request	-> Ask access to a study
Both will be independent (even if done at the same time).
There will be no more "administrator acceptation", only the studies managers will decide if a user can join or not the study.

I) New user
When creating a new request account the user will be able to create an access request on different studies.
- Either from the list of 'public available' studies
- Either from a text field the user needs to fill with a specific code associated to the study.

For every study, add a new column containing a code automatically generated.
The study administrator can give it to the new user so that he can request an access to the study.
When the study manager connects, he sees the study access demand and can accept/refuse it.

II) Existing user
When an existing user wants to join a study, he clicks on a button on the top of the study list to ask for an access. He has the same options as the new user:
- Either from the list of 'public available' studies
- Either from a text field the user needs to fill with a specific code.

StudyAccessDemand
- Id
- Date
- Status
- Motivation text
- User ID
- Study ID
- Expiration date ?

The study administrator receives an email with the access request, and can choose to accept it or refuse it.
This response will be sent to the user in an email and will trigger the subscription (or not) of the user to the study.

Requirement: An user within no study should not be able to have access to anything in Shanoir
**Solution 1**: The account user is not activated (he can't connect) until accepted in a study -> This means an account demand must obligatorily contain an access demand.
If refused (no demands pending, no access to any study), the account will be deleted.

**Solution 2**: A (new) user linked to no study should be automatically redirected to the study access request page (and have access to nothing else).
For this, we create a keycloak key by user 'hasAccessToStudy' that will be updated if an user enters / leaves a study.
Then add an automatic "redirect" to this access page if the user has this key activated.
-> https://stackoverflow.com/questions/43487827/how-to-apply-canactivate-guard-on-all-the-routes (we redirect automatically to /accessRequest if no study)

TODO list:
- Add visible by default on study (false by default) -> describe what is it for in front (XS)
- Remove list of users for experts (cannot add an user to the study) -> Only for admins (XS)
- Add study unique key system (generated once, the first time it is asked by the study manager) (XS)
- Mix account request (challenge and not chalenge) and add access request to the page (M)
- Add a page for access request (S)
- Manage access request acception / refusal (+front) (M)
(1)
- Add a "hasAccessToStudy" key on every keycloak user and manage it on user subscription/deletion from a study (M)
- Redirect user with no study (S)
(2)
- Activate an account only when the user is accepted in a study (XS)
- Trigger account deletion when rejected / deleted from a study (and no other study / pending access demand) (XS)

What if a new user wants to create a new study ? Is it possible ? -> Not for the moment (newly created users will be 'users' until further news)

Other idea:
Add a notion of "Group of studies" that put multiples studies in a same logical entity.
- An user can only see the users that are part of the realm/group
- A newly subscribed user is part of all the studies of the realm/group
- Split referential by group/realm (a center is modified only in its realm, referential is duplicated)
--> What about single study realms ? (Do they have to recreate all the referential ?)

**Comment by michaelkain** [comment]
DONE
