### ISSUE TITLE
[Import] verify that import success email is really send at the end

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#918]
Hi Jean-Come,
could you please analyse and maybe adapt a functionality during my absence (based on an OFSEP feedback):
We need to assure, that an import is really completely finished and complet, when the import email is sent.
In the OFSEP context, the users of ShUp will not verify on the server if the images arrived, they wait for the
email and consider the email as final criteria of success. Could you analyse, that the email is send at the end
of all import processing? if not, please adapt it. I am thinking, if we should even add some code, that walks
through all created datasets and runs a HTTP-HEAD against the internal pacs of Shanoir to verify if all images
are present (200 OK feedback) for the dicoms and a file.exists on the disk for all nifti files. I think this issue is
quite an important extension.
With kind regards and have a good week,
Michael

**Comment by jcomedouteau** [comment]
The email sending is currently based on the event, when the import event is set "in success", then the mail is send with the informations contained in this event.
This event is set to success at the end of the import so normally it is sent only when the import was a total success.

Did they meet a case where it was sent but the data wasn't present ?

By the way, I already found out some datasets that had some missing dicom/niftis (and faulty DB logic)
https://github.com/fli-iam/shanoir-ng/issues/778
They are all coming from the old shanoir database I think and it is really weird but I could not explain where the bug was coming from.

Jean-Côme
