### ISSUE TITLE
[OFSEP] import confirmation email extension

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#930]
OFSEP feedback: add missing elements back to import confirmation email:
- exam date (old: importReportBean.getExamination().getDisplayString())
- study card (old: dicomImporter.getStudyCard().getName())
These elements have been present in sh-old and are very helpful for the OFSEP centers.

**Comment by michaelkain** [comment]
Hi Jean-Come, I have started to investigate on this and if this is okay for you, I would like to ask you for a refactoring please. If okay for you could you please integrate the above extension too. I think the current implementation, that parses the message string of the event is very sensitive to errors.
ms import - ImporterService:
			event.setMessage(importJob.getStudyName() + "(" + importJob.getStudyId() + ")"
			+": Successfully created datasets for subject " + importJob.getSubjectName()
			+ " in examination " + examination.getId());
			eventService.publishEvent(event);
ms users - EmailServiceImpl
		String patternStr = "(.*)\\((\\d+)\\)\\: Successfully created datasets for subject (.*) in examination (\\d+)";
        Pattern pattern = Pattern.compile(patternStr);

Furthermore, if I remember right, I have asked you in a pull request to please rename the below method, as this method is not searching users, that have the right can_admin, but all users, that have checked the receiveImportEmail flag:
	public List<Long> getStudyAdministrator(String studyId) {
		try {
			List<Long> response =  (List<Long>) rabbitTemplate.convertSendAndReceive(RabbitMQConfiguration.USER_ADMIN_STUDY_QUEUE, studyId);

To completely avoid the above call to ms studies (time demanding and error prone in a microservice environment) I would propose to use the same logic as e.g. in ms datasets (code already exists) that duplicates study_user and study_user_rights into ms users. So, ms users would be updated of all changes on study_user, if done, and will not have to ask ms studies for these informations for every import mail to send.

**Comment by jcomedouteau** [comment]
Hi Michael,

Yes we talked about this method, you are right I'll rename it.
I'm not really fond of  this information duplication but as we already do it at multiple place it may be quite more simple to implement.

Th event parsing is not really error prone as it is correctly unit tested and commented when the event is created => normally it won't change.
If we want to reduce code duplication and inter-microservice communications, it felt like an adapted solution

Another solution I see is to have an "Email template" (common Class ?) prepared in MS datasets with all necessary informations then transmitted using rabbitMQ.
Using this: 
- There is only one unique rabbitMQ communication (only if necessary) 
- Transporting a single common object (no parsing error prone problem) with all needed data and easily updatable
- There is no need to duplicate study_user information in user microservice
- No need for this method that gets emails waiting users (then we delete it rather than renaming it)

**Comment by michaelkain** [comment]
Hi Jean-Come, would it be easily possible to add links to datasets into the email using a template and the dsId, just an idea, that could be nice :-)
